/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: LPC5514
package_id: LPC5514JBD64
mcu_data: ksdk2_0
processor_version: 24.12.10
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: ef474440-ae86-47d2-b0ce-9b7b9cffcd90
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'lpc_dma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'lpc_dma_2.5.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_dma:
    - dma_table:
      - 0: []
    - dma_channels:
      - 0:
        - apiMode: 'trans'
        - dma_channel:
          - channel_prefix_id: 'CH0'
          - DMA_source: 'kDma0RequestADC0FIFO0'
          - init_channel_priority: 'false'
          - dma_priority: 'kDMA_ChannelPriority0'
          - enable_custom_name: 'false'
        - peripheral_request: 'true'
        - init_trigger_config: 'false'
        - trigger_config:
          - type: 'kDMA_RisingEdgeTrigger'
          - burst: 'kDMA_SingleTransfer'
          - wrap: 'kDMA_NoWrap'
        - trans_config:
          - init_callback: 'false'
          - callback_function: ''
          - callback_user_data: ''
        - tcd_config: []
        - allocateTCD: 'noncache'
        - initTCD: 'noTCDInit'
    - dma_interrupt_trans:
      - IRQn: 'DMA0_IRQn'
      - enable_priority: 'true'
      - priority: '1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

  /* Channel CH0 global variables */
dma_handle_t DMA0_CH0_Handle;

static void DMA0_init(void) {
  /* Interrupt vector DMA0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(DMA0_IRQN, DMA0_IRQ_PRIORITY);

  /* Channel CH0 initialization */
  /* Enable the DMA 21 channel in the DMA */
  DMA_EnableChannel(DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
  /* Create the DMA DMA0_CH0_Handle handle */
  DMA_CreateHandle(&DMA0_CH0_Handle, DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
  DMA_EnableChannelPeriphRq(DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
}

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
    - interrupts:
      - 0:
        - channelId: 'Flexcomm_nmea'
        - interrupt_t:
          - IRQn: 'FLEXCOMM0_IRQn'
          - enable_interrrupt: 'noInit'
          - enable_priority: 'true'
          - priority: '2'
          - enable_custom_name: 'false'
      - 1:
        - channelId: 'Flexcomm_usart'
        - interrupt_t:
          - IRQn: 'FLEXCOMM2_IRQn'
          - enable_interrrupt: 'noInit'
          - enable_priority: 'true'
          - priority: '2'
          - enable_custom_name: 'false'
      - 2:
        - channelId: 'ADC'
        - interrupt_t:
          - IRQn: 'ADC0_IRQn'
          - enable_interrrupt: 'noInit'
          - enable_priority: 'true'
          - priority: '3'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * FLEXCOMM_I2C initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXCOMM_I2C'
- type: 'flexcomm_i2c'
- mode: 'freertos'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_2.3.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM1'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - rtos_handle:
      - enable_custom_name: 'false'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '100000'
      - enableTimeout: 'false'
      - timeout_Ms: '35'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM1_IRQn'
      - enable_priority: 'true'
      - priority: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
i2c_rtos_handle_t FLEXCOMM_I2C_rtosHandle;
const i2c_master_config_t FLEXCOMM_I2C_config = {
  .enableMaster = true,
  .baudRate_Bps = 100000UL,
  .enableTimeout = false,
  .timeout_Ms = 35U
};

static void FLEXCOMM_I2C_init(void) {
  /* Initialization function */
  I2C_RTOS_Init(&FLEXCOMM_I2C_rtosHandle, FLEXCOMM_I2C_PERIPHERAL, &FLEXCOMM_I2C_config, FLEXCOMM_I2C_CLOCK_SOURCE);
  /* Interrupt vector FLEXCOMM1_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(FLEXCOMM_I2C_FLEXCOMM_IRQN, FLEXCOMM_I2C_FLEXCOMM_IRQ_PRIORITY);
}

/***********************************************************************************************************************
 * FLEXCOMM_SPI initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXCOMM_SPI'
- type: 'flexcomm_spi'
- mode: 'freertos'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_spi_2.3.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM3'
- config_sets:
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - rtos_handle:
      - enable_custom_name: 'false'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveHigh'
      - phase: 'kSPI_ClockPhaseSecondEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '500000'
      - dataWidth: 'kSPI_Data16Bits'
      - sselNum: 'kSPI_Ssel0'
      - sselPol_set: ''
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '0'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM3_IRQn'
      - enable_priority: 'true'
      - priority: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
spi_rtos_handle_t FLEXCOMM_SPI_rtosHandle;
const spi_master_config_t FLEXCOMM_SPI_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveHigh,
  .phase = kSPI_ClockPhaseSecondEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 500000UL,
  .dataWidth = kSPI_Data16Bits,
  .sselNum = kSPI_Ssel0,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 0U,
    .postDelay = 0U,
    .frameDelay = 0U,
    .transferDelay = 0U
  }
};

static void FLEXCOMM_SPI_init(void) {
  /* Initialization function */
  SPI_RTOS_Init(&FLEXCOMM_SPI_rtosHandle, FLEXCOMM_SPI_PERIPHERAL, &FLEXCOMM_SPI_config, FLEXCOMM_SPI_CLOCK_SOURCE);
  /* Interrupt vector FLEXCOMM3_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(FLEXCOMM_SPI_FLEXCOMM_IRQN, FLEXCOMM_SPI_FLEXCOMM_IRQ_PRIORITY);
}

/***********************************************************************************************************************
 * FLEXCOMM_UART initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXCOMM_UART'
- type: 'flexcomm_usart'
- mode: 'polling'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_usart_2.8.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM0'
- config_sets:
  - usartConfig_t:
    - usartConfig:
      - clockSource: 'FXCOMFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '115200'
      - syncMode: 'kUSART_SyncModeDisabled'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - txWatermark: 'kUSART_TxFifo0'
      - rxWatermark: 'kUSART_RxFifo1'
      - enableMatchAddress: 'false'
      - matchAddressConfig:
        - matchAddress: '0'
        - addressMode: 'automatic'
      - enableRx: 'true'
      - enableTx: 'true'
      - enableHardwareFlowControl: 'false'
      - enableRTS: 'false'
      - clockPolarity: 'kUSART_RxSampleOnFallingEdge'
      - enableContinuousSCLK: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t FLEXCOMM_UART_config = {
  .baudRate_Bps = 115200UL,
  .syncMode = kUSART_SyncModeDisabled,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .txWatermark = kUSART_TxFifo0,
  .rxWatermark = kUSART_RxFifo1,
  .enableRx = true,
  .enableTx = true,
  .enableHardwareFlowControl = false,
  .enableMode32k = false,
  .clockPolarity = kUSART_RxSampleOnFallingEdge,
  .enableContinuousSCLK = false
};

static void FLEXCOMM_UART_init(void) {
  USART_Init(FLEXCOMM_UART_PERIPHERAL, &FLEXCOMM_UART_config, FLEXCOMM_UART_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * CRC_ENGINE initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CRC_ENGINE'
- type: 'lpc_crc'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'lpc_crc_2.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CRC_ENGINE'
- config_sets:
  - fsl_crc:
    - crc_config:
      - polynomial: 'kCRC_Polynomial_CRC_CCITT'
      - reverseIn: 'false'
      - complementIn: 'false'
      - reverseOut: 'false'
      - complementOut: 'false'
      - seed: '0xFFFF'
    - quick_selection: 'crc_ccit'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const crc_config_t CRC_ENGINE_config = {
  .polynomial = kCRC_Polynomial_CRC_CCITT,
  .reverseIn = false,
  .complementIn = false,
  .reverseOut = false,
  .complementOut = false,
  .seed = 0xFFFFUL
};

static void CRC_ENGINE_init(void) {
  CRC_Init(CRC_ENGINE_PERIPHERAL, &CRC_ENGINE_config);
}

/***********************************************************************************************************************
 * CAN0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CAN0'
- type: 'mcan'
- mode: 'interrupts'
- custom_name_enabled: 'false'
- type_id: 'mcan_2.1.3'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CAN0'
- config_sets:
  - interruptsCfg:
    - txBufferInterruptSources:
      - txBufferInterruptSources_L:
        - 0: 'disabled'
        - 1: 'disabled'
        - 2: 'disabled'
        - 3: 'disabled'
        - 4: 'disabled'
        - 5: 'disabled'
        - 6: 'disabled'
        - 7: 'disabled'
        - 8: 'disabled'
        - 9: 'disabled'
        - 10: 'disabled'
        - 11: 'disabled'
        - 12: 'disabled'
        - 13: 'disabled'
        - 14: 'disabled'
        - 15: 'disabled'
      - txBufferInterruptSources_H:
        - 0: 'disabled'
        - 1: 'disabled'
        - 2: 'disabled'
        - 3: 'disabled'
        - 4: 'disabled'
        - 5: 'disabled'
        - 6: 'disabled'
        - 7: 'disabled'
        - 8: 'disabled'
        - 9: 'disabled'
        - 10: 'disabled'
        - 11: 'disabled'
        - 12: 'disabled'
        - 13: 'disabled'
        - 14: 'disabled'
        - 15: 'disabled'
    - interrupts:
      - 0:
        - interrupts: ''
        - enable_irq: 'false'
        - interrupt_line:
          - IRQn: 'CAN0_IRQ0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
      - 1:
        - interrupts: ''
        - enable_irq: 'false'
        - interrupt_line:
          - IRQn: 'CAN0_IRQ1_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
    - quick_selection: 'default'
  - fsl_mcan:
    - mcanConfig:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - baudRateA: '500000'
      - baudRateD: '1000000'
      - enableCanfdNormal: 'false'
      - enableCanfdSwitch: 'false'
      - loopBackBusMonMode: 'kMCAN_disabled'
      - setNormalOperation: 'true'
      - nominalBitTiming:
        - seg1: '11'
        - seg2: '4'
        - rJumpwidth: '4'
        - bitTime: []
      - dataBitTiming:
        - seg1: '11'
        - seg2: '4'
        - rJumpwidth: '4'
        - bitTime: []
      - timingConfig: []
    - messagesConfig:
      - enable_custom_name: 'false'
      - allocateRAM: 'false'
      - stdFilter:
        - listSize: '1'
        - remFrame: 'kMCAN_rejectFrame'
        - nmFrame: 'kMCAN_reject0'
      - extFilter:
        - listSize: '0'
        - remFrame: 'kMCAN_rejectFrame'
        - nmFrame: 'kMCAN_reject0'
      - rxFifo0:
        - elementSize: '1'
        - watermark: '0'
        - opmode: 'kMCAN_FifoBlocking'
        - datafieldSize: 'kMCAN_8ByteDatafield'
      - rxFifo1:
        - elementSize: '0'
        - watermark: '0'
        - opmode: 'kMCAN_FifoBlocking'
        - datafieldSize: 'kMCAN_8ByteDatafield'
      - rxBuffer:
        - elementSize: '0'
        - datafieldSize: 'kMCAN_8ByteDatafield'
      - txFifo:
        - elementSize: '0'
        - watermark: '0'
      - txBuffer:
        - dedicatedSize: '1'
        - fqSize: '0'
        - mode: 'kMCAN_txFifo'
        - datafieldSize: 'kMCAN_8ByteDatafield'
    - stdFilters: []
    - extFilters: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const mcan_config_t CAN0_config = {
  .baudRateA = 500000UL,
  .baudRateD = 1000000UL,
  .enableCanfdNormal = false,
  .enableCanfdSwitch = false,
  .enableLoopBackInt = false,
  .enableLoopBackExt = false,
  .enableBusMon = false,
  .timingConfig = {
    .preDivider = 0,
    .rJumpwidth = 3,
    .seg1 = 10,
    .seg2 = 3,
    .datapreDivider = 0,
    .datarJumpwidth = 3,
    .dataseg1 = 10,
    .dataseg2 = 3
  }
};
const mcan_frame_filter_config_t CAN0_std_filter_config = {
  .address = 0,
  .listSize = 1UL,
  .idFormat = kMCAN_FrameIDStandard,
  .remFrame = kMCAN_rejectFrame,
  .nmFrame = kMCAN_reject0
};
const mcan_frame_filter_config_t CAN0_ext_filter_config = {
  .address = 4,
  .listSize = 0UL,
  .idFormat = kMCAN_FrameIDExtend,
  .remFrame = kMCAN_rejectFrame,
  .nmFrame = kMCAN_reject0
};
const mcan_rx_fifo_config_t CAN0_rx_fifo0_config = {
  .address = 4,
  .elementSize = 1UL,
  .watermark = 0UL,
  .opmode = kMCAN_FifoBlocking,
  .datafieldSize = kMCAN_8ByteDatafield
};
const mcan_rx_fifo_config_t CAN0_rx_fifo1_config = {
  .address = 20,
  .elementSize = 0UL,
  .watermark = 0UL,
  .opmode = kMCAN_FifoBlocking,
  .datafieldSize = kMCAN_8ByteDatafield
};
const mcan_rx_buffer_config_t CAN0_rx_buffers_config = {
  .address = 20,
  .datafieldSize = kMCAN_8ByteDatafield
};
const mcan_tx_fifo_config_t CAN0_tx_event_fifo_config = {
  .address = 20,
  .elementSize = 0UL,
  .watermark = 0UL
};
const mcan_tx_buffer_config_t CAN0_tx_buffers_config = {
  .address = 20,
  .dedicatedSize = 1UL,
  .fqSize = 0UL,
  .mode = kMCAN_txFifo,
  .datafieldSize = kMCAN_8ByteDatafield
};

static void CAN0_init(void) {
  /* MCAN initialization */
  MCAN_Init(CAN0_PERIPHERAL, &CAN0_config, CAN0_CLOCK_SOURCE);
  /* Message RAM initialization */
  memset(CAN0_RAM_BASE_ADDRESS, 0,CAN0_MESSAGE_RAM_SIZE * sizeof(uint32_t));
  MCAN_SetMsgRAMBase(CAN0_PERIPHERAL, (uint32_t)CAN0_RAM_BASE_ADDRESS);
  /* Configuration of the standard filter list */
  MCAN_SetFilterConfig(CAN0_PERIPHERAL, &CAN0_std_filter_config);
  /* Configuration of the extended filter list */
  MCAN_SetFilterConfig(CAN0_PERIPHERAL, &CAN0_ext_filter_config);
  /* Configuration of Rx FIFO 0 */
  MCAN_SetRxFifo0Config(CAN0_PERIPHERAL, &CAN0_rx_fifo0_config);
  /* Configuration of Rx FIFO 1 */
  MCAN_SetRxFifo1Config(CAN0_PERIPHERAL, &CAN0_rx_fifo1_config);
  /* Configuration of Rx buffers */
  MCAN_SetRxBufferConfig(CAN0_PERIPHERAL, &CAN0_rx_buffers_config);
  /* Configuration of Tx event FIFO */
  MCAN_SetTxEventFifoConfig(CAN0_PERIPHERAL, &CAN0_tx_event_fifo_config);
  /* Configuration of Tx buffers and FIFO/Queue */
  MCAN_SetTxBufferConfig(CAN0_PERIPHERAL, &CAN0_tx_buffers_config);
  /* Setting of the CAN normal mode to start communication */
  MCAN_EnterNormalMode(CAN0_PERIPHERAL);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void BOARD_InitPeripherals_CommonPostInit(void)
{
  /* Interrupt vector FLEXCOMM0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(FLEXCOMM_NMEA_IRQN, FLEXCOMM_NMEA_IRQ_PRIORITY);
  /* Interrupt vector FLEXCOMM2_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(FLEXCOMM_USART_IRQN, FLEXCOMM_USART_IRQ_PRIORITY);
  /* Interrupt vector ADC0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(ADC_IRQN, ADC_IRQ_PRIORITY);
  /* Interrupt FLEXCOMM_NMEA_IRQN request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(FLEXCOMM_NMEA_IRQN); function call. */
  /* Interrupt FLEXCOMM_USART_IRQN request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(FLEXCOMM_USART_IRQN); function call. */
  /* Interrupt ADC_IRQN request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(ADC_IRQN); function call. */
}

void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMA_Init(DMA0_DMA_BASEADDR);

  /* Initialize components */
  DMA0_init();
  FLEXCOMM_I2C_init();
  FLEXCOMM_SPI_init();
  FLEXCOMM_UART_init();
  CRC_ENGINE_init();
  CAN0_init();
  /* Common post-initialization */
  BOARD_InitPeripherals_CommonPostInit();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
