/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_dma.h"
#include "fsl_common.h"
#include "fsl_i2c.h"
#include "fsl_i2c_freertos.h"
#include "fsl_spi.h"
#include "fsl_spi_freertos.h"
#include "fsl_lpadc.h"
#include "fsl_power.h"
#include "fsl_reset.h"
#include "fsl_usart.h"
#include "fsl_clock.h"
#include "fsl_crc.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR DMA0
/* DMA0 interrupt vector ID (number). */
#define DMA0_IRQN DMA0_IRQn
/* DMA0 interrupt vector priority. */
#define DMA0_IRQ_PRIORITY 1

  /* Channel CH0 definitions */
/* Selected DMA channel number. */
#define DMA0_CH0_DMA_CHANNEL 21
/* NVIC interrupt vector ID (number). */
#define FLEXCOMM_NMEA_IRQN FLEXCOMM0_IRQn
/* NVIC interrupt vector priority. */
#define FLEXCOMM_NMEA_IRQ_PRIORITY 2
/* NVIC interrupt handler identifier. */
#define FLEXCOMM_NMEA_IRQHANDLER FLEXCOMM0_IRQHandler
/* NVIC interrupt vector ID (number). */
#define FLEXCOMM_USART_IRQN FLEXCOMM2_IRQn
/* NVIC interrupt vector priority. */
#define FLEXCOMM_USART_IRQ_PRIORITY 2
/* NVIC interrupt handler identifier. */
#define FLEXCOMM_USART_IRQHANDLER FLEXCOMM2_IRQHandler
/* NVIC interrupt vector ID (number). */
#define ADC_IRQN ADC0_IRQn
/* NVIC interrupt vector priority. */
#define ADC_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define ADC_IRQHANDLER ADC0_IRQHandler
/* BOARD_InitPeripherals defines for FLEXCOMM1 */
/* Definition of peripheral ID */
#define FLEXCOMM_I2C_PERIPHERAL ((I2C_Type *)FLEXCOMM1)
/* Definition of the clock source frequency */
#define FLEXCOMM_I2C_CLOCK_SOURCE 15014662UL
/* FLEXCOMM_I2C interrupt vector ID (number). */
#define FLEXCOMM_I2C_FLEXCOMM_IRQN FLEXCOMM1_IRQn
/* FLEXCOMM_I2C interrupt vector priority. */
#define FLEXCOMM_I2C_FLEXCOMM_IRQ_PRIORITY 2
/* BOARD_InitPeripherals defines for FLEXCOMM3 */
/* Definition of peripheral ID */
#define FLEXCOMM_SPI_PERIPHERAL ((SPI_Type *)FLEXCOMM3)
/* Definition of the clock source frequency */
#define FLEXCOMM_SPI_CLOCK_SOURCE 15014662UL
/* FLEXCOMM_SPI interrupt vector ID (number). */
#define FLEXCOMM_SPI_FLEXCOMM_IRQN FLEXCOMM3_IRQn
/* FLEXCOMM_SPI interrupt vector priority. */
#define FLEXCOMM_SPI_FLEXCOMM_IRQ_PRIORITY 2
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* Command 1 - THERMISTOR */
#define ADC0_THERMISTOR 1U
/* Command 2 - ECHO */
#define ADC0_ECHO 2U
/* Command 3 - CPU_TEMP */
#define ADC0_CPU_TEMP 3U
/* Trigger 2 - ECHO_TRIGGER */
#define ADC0_ECHO_TRIGGER 2U
/* Trigger 0 - THERM_TRIGGER */
#define ADC0_THERM_TRIGGER 0U
/* Definition of peripheral ID */
#define FLEXCOMM_USART_PERIPHERAL ((USART_Type *)FLEXCOMM2)
/* Definition of the clock source frequency */
#define FLEXCOMM_USART_CLOCK_SOURCE 15014662UL
/* Definition of peripheral ID */
#define FLEXCOMM_NMEA_PERIPHERAL ((USART_Type *)FLEXCOMM0)
/* Definition of the clock source frequency */
#define FLEXCOMM_NMEA_CLOCK_SOURCE 15014662UL
/* Definition of peripheral ID */
#define CRC_ENGINE_PERIPHERAL CRC_ENGINE

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern dma_handle_t DMA0_CH0_Handle;
extern i2c_rtos_handle_t FLEXCOMM_I2C_rtosHandle;
extern const i2c_master_config_t FLEXCOMM_I2C_config;
extern spi_rtos_handle_t FLEXCOMM_SPI_rtosHandle;
extern const spi_master_config_t FLEXCOMM_SPI_config;
extern const lpadc_config_t ADC0_config;
extern lpadc_conv_command_config_t ADC0_commandsConfig[3];
extern lpadc_conv_trigger_config_t ADC0_triggersConfig[2];
extern const usart_config_t FLEXCOMM_USART_config;
extern const usart_config_t FLEXCOMM_NMEA_config;
extern const crc_config_t CRC_ENGINE_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
