/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_dma.h"
#include "fsl_common.h"
#include "fsl_i2c.h"
#include "fsl_i2c_freertos.h"
#include "fsl_spi.h"
#include "fsl_spi_freertos.h"
#include "fsl_reset.h"
#include "fsl_usart.h"
#include "fsl_clock.h"
#include "fsl_crc.h"
#include "fsl_mcan.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR DMA0
/* DMA0 interrupt vector ID (number). */
#define DMA0_IRQN DMA0_IRQn
/* DMA0 interrupt vector priority. */
#define DMA0_IRQ_PRIORITY 1

  /* Channel CH0 definitions */
/* Selected DMA channel number. */
#define DMA0_CH0_DMA_CHANNEL 21
/* NVIC interrupt vector ID (number). */
#define FLEXCOMM_NMEA_IRQN FLEXCOMM0_IRQn
/* NVIC interrupt vector priority. */
#define FLEXCOMM_NMEA_IRQ_PRIORITY 2
/* NVIC interrupt handler identifier. */
#define FLEXCOMM_NMEA_IRQHANDLER FLEXCOMM0_IRQHandler
/* NVIC interrupt vector ID (number). */
#define FLEXCOMM_USART_IRQN FLEXCOMM2_IRQn
/* NVIC interrupt vector priority. */
#define FLEXCOMM_USART_IRQ_PRIORITY 2
/* NVIC interrupt handler identifier. */
#define FLEXCOMM_USART_IRQHANDLER FLEXCOMM2_IRQHandler
/* NVIC interrupt vector ID (number). */
#define ADC_IRQN ADC0_IRQn
/* NVIC interrupt vector priority. */
#define ADC_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define ADC_IRQHANDLER ADC0_IRQHandler
/* BOARD_InitPeripherals defines for FLEXCOMM1 */
/* Definition of peripheral ID */
#define FLEXCOMM_I2C_PERIPHERAL ((I2C_Type *)FLEXCOMM1)
/* Definition of the clock source frequency */
#define FLEXCOMM_I2C_CLOCK_SOURCE 37536656UL
/* FLEXCOMM_I2C interrupt vector ID (number). */
#define FLEXCOMM_I2C_FLEXCOMM_IRQN FLEXCOMM1_IRQn
/* FLEXCOMM_I2C interrupt vector priority. */
#define FLEXCOMM_I2C_FLEXCOMM_IRQ_PRIORITY 2
/* BOARD_InitPeripherals defines for FLEXCOMM3 */
/* Definition of peripheral ID */
#define FLEXCOMM_SPI_PERIPHERAL ((SPI_Type *)FLEXCOMM3)
/* Definition of the clock source frequency */
#define FLEXCOMM_SPI_CLOCK_SOURCE 37536656UL
/* FLEXCOMM_SPI interrupt vector ID (number). */
#define FLEXCOMM_SPI_FLEXCOMM_IRQN FLEXCOMM3_IRQn
/* FLEXCOMM_SPI interrupt vector priority. */
#define FLEXCOMM_SPI_FLEXCOMM_IRQ_PRIORITY 2
/* Definition of peripheral ID */
#define FLEXCOMM_UART_PERIPHERAL ((USART_Type *)FLEXCOMM0)
/* Definition of the clock source frequency */
#define FLEXCOMM_UART_CLOCK_SOURCE 37536656UL
/* Definition of peripheral ID */
#define CRC_ENGINE_PERIPHERAL CRC_ENGINE
/* Definition of peripheral ID */
#define CAN0_PERIPHERAL CAN0
/* Definition of the clock source frequency */
#define CAN0_CLOCK_SOURCE 1500000UL
/* Definition of the base address alignment */
#define CAN0_BASE_ADDRESS_ALIGN_SIZE (0x10000)
/* Definition of the message RAM size in words */
#define CAN0_MESSAGE_RAM_SIZE 9
/* Nominal baud rate value (calculated) */
#define CAN0_NOMINAL_BAUD_RATE_VALUE 93750
/* Mask of enabled TX buffer interrupts */
#define CAN0_TX_BUFFERS_IRQ_MASK 0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern dma_handle_t DMA0_CH0_Handle;
extern i2c_rtos_handle_t FLEXCOMM_I2C_rtosHandle;
extern const i2c_master_config_t FLEXCOMM_I2C_config;
extern spi_rtos_handle_t FLEXCOMM_SPI_rtosHandle;
extern const spi_master_config_t FLEXCOMM_SPI_config;
extern const usart_config_t FLEXCOMM_UART_config;
extern const crc_config_t CRC_ENGINE_config;
extern const mcan_config_t CAN0_config;
extern uint32_t CAN0_RAM_BASE_ADDRESS[CAN0_MESSAGE_RAM_SIZE];
extern const mcan_frame_filter_config_t CAN0_std_filter_config;
extern const mcan_frame_filter_config_t CAN0_ext_filter_config;
extern const mcan_rx_fifo_config_t CAN0_rx_fifo0_config;
extern const mcan_rx_fifo_config_t CAN0_rx_fifo1_config;
extern const mcan_rx_buffer_config_t CAN0_rx_buffers_config;
extern const mcan_tx_fifo_config_t CAN0_tx_event_fifo_config;
extern const mcan_tx_buffer_config_t CAN0_tx_buffers_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
