/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_0_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO0_10_FUNC_ALT6 0x06u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_11_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO0_11_FUNC_ALT6 0x06u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_12_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO0_12_FUNC_ALT6 0x06u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_13_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_14_FUNC_ALT1 0x01u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO0_15_ASW_VALUE1 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO0_15_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_15_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_15_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO0_16_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 4. */
#define PIO0_17_FUNC_ALT4 0x04u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 4. */
#define PIO0_18_FUNC_ALT4 0x04u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_19_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO0_1_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_20_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_22_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO0_22_FUNC_ALT7 0x07u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_23_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 4. */
#define PIO0_23_FUNC_ALT4 0x04u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_27_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_27_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_29_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_29_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_2_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_30_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_30_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_3_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_4_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_4_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_6_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_6_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_7_FUNC_ALT0 0x00u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO1_0_ASW_VALUE1 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO1_0_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_0_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_0_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 4. */
#define PIO1_1_FUNC_ALT4 0x04u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO1_2_FUNC_ALT3 0x03u

/*! @name PIO0_0 (number 36), ECHO_IN2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ECHO_IN2_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ECHO_IN2_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_ECHO_IN2_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ECHO_IN2_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ECHO_IN2_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_2 (number 52), ECHO_MISO
  @{ */
#define BOARD_INITPINS_ECHO_MISO_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ECHO_MISO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ECHO_MISO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_3 (number 53), ECHO_MOSI
  @{ */
#define BOARD_INITPINS_ECHO_MOSI_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ECHO_MOSI_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ECHO_MOSI_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_4 (number 55), ECHO_IN1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ECHO_IN1_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ECHO_IN1_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_ECHO_IN1_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ECHO_IN1_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ECHO_IN1_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_6 (number 57), ECHO_SCLK
  @{ */
#define BOARD_INITPINS_ECHO_SCLK_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ECHO_SCLK_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ECHO_SCLK_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_13 (number 46), I2C_SDA
  @{ */
#define BOARD_INITPINS_I2C_SDA_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_SDA_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_SDA_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_14 (number 47), I2C_SCL
  @{ */
#define BOARD_INITPINS_I2C_SCL_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_SCL_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_SCL_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_15 (number 14), ADC_THERMISTOR
  @{ */
#define BOARD_INITPINS_ADC_THERMISTOR_GPIO GPIO                 /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_ADC_THERMISTOR_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_THERMISTOR_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_THERMISTOR_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PIO0_16 (number 7), CLKOUT
  @{ */
#define BOARD_INITPINS_CLKOUT_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CLKOUT_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CLKOUT_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_17 (number 3), ECHO_PWM1
  @{ */
#define BOARD_INITPINS_ECHO_PWM1_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ECHO_PWM1_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ECHO_PWM1_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_18 (number 38), ECHO_PWM2
  @{ */
#define BOARD_INITPINS_ECHO_PWM2_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ECHO_PWM2_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ECHO_PWM2_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_19 (number 58), LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_20 (number 48), DBG
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DBG_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DBG_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_DBG_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_DBG_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DBG_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DBG_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_27 (number 18), PORT1_TXD
  @{ */
#define BOARD_INITPINS_PORT1_TXD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PORT1_TXD_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PORT1_TXD_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_29 (number 59), PORT0_RXD
  @{ */
#define BOARD_INITPINS_PORT0_RXD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PORT0_RXD_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PORT0_RXD_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_30 (number 60), PORT0_TXD
  @{ */
#define BOARD_INITPINS_PORT0_TXD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PORT0_TXD_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PORT0_TXD_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO1_0 (number 4), ADC_ECHO
  @{ */
#define BOARD_INITPINS_ADC_ECHO_GPIO GPIO                /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_ADC_ECHO_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_ECHO_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_ECHO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_1 (number 2), ECHO_CS
  @{ */
#define BOARD_INITPINS_ECHO_CS_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ECHO_CS_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ECHO_CS_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_7 (number 1), HIGH_POWER
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HIGH_POWER_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HIGH_POWER_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HIGH_POWER_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_HIGH_POWER_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HIGH_POWER_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HIGH_POWER_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
